---
- name: Provision an EC2 Instance
  hosts: local
  connection: local
  pre_tasks:
    - { include: roles/ec2/tasks/setup_boto.yml, tags: [ 'provisioning', 'setupboto' ] }
    - { include: roles/ec2/tasks/create_vpc.yml, tags: [ 'provisioning', 'createvpc' ] }
    - { include: roles/ec2/tasks/create_subnet.yml, tags: [ 'provisioning', 'createsubnet' ] }
    - { include: roles/ec2/tasks/create_security_group.yml, tags: [ 'provisioning', 'createsg'] }
  roles:
      - { role: ec2 }


