---
- name: Configure Oracle Linux 7 with Oracle Database 12c
  hosts: oracle_db
  become: True
  vars_files:
    # User Passwords
    - oracle_secrets.yml
  roles:
    - role: linux-oracle
    - role: oracle-install
      become_user: '{{ oracle_user }}'

