---


- name: Create group
  group: 
    name: "{{ item.groups }}"
    state: present
  with_items: "{{ user_list }}"


- name: Create new users 
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
    state: present
  with_items: "{{ user_list }}"


