---

- name: Launch the new EC2 Instance
  local_action: ec2 
    group={{ security_group }} 
    instance_type={{ instance_type}} 
    image={{ image }} 
    wait=true 
    region={{ region }} 
    keypair={{ keypair }}
    count={{count}}
    volumes={{instance_volumes}}
    zone={{ zone }}
    vpc_subnet_id={{ vpc_subnet }}
    instance_tags={{ host_tag }}
    aws_access_key={{ec2_access_key}}
    aws_secret_key={{ec2_secret_key}}
  register: ec2

#- name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
#  local_action: lineinfile 
#    dest={{ hosts_ini_file }}
#    regexp={{ item.public_ip }} 
#    insertafter="\[{{host_tag.group}}\]" line={{ item.public_ip }}
#  with_items: "{{ ec2.instances }}"


# set host_ip_addr to public ip if specified else private ip as default
#- name: Get IP of newly created instance
#  set_fact: 
#    host_ip_addr: "{% if public_ip_in_ini %} {{ item.public_ip }} {% else %} {{ item.private_ip }} {% endif %}"
#  with_items: "{{ ec2.instances }}"
  

- name: Add public ip of the newly created EC2 instance(s) to the local host group (located inside the directory)
  local_action: lineinfile
    dest={{ hosts_ini_file }}
    regexp={{ item.public_ip }}
    insertafter="\[{{hosts_tag_group}}\]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"
  when: public_ip_in_ini is defined and public_ip_in_ini

  
- name: Add private ip of the newly created EC2 instance(s) to the local host group (located inside the directory)
  local_action: lineinfile
    dest={{ hosts_ini_file }}
    regexp={{ item.private_ip }}
    insertafter="\[{{hosts_tag_group}}\]" line={{ item.private_ip }}
  with_items: "{{ ec2.instances }}"
  when: public_ip_in_ini is not defined or public_ip_in_ini == False


#- name: setup SSH Key
#  shell: "sh {{ role_path }}/files/setup_key.sh {{ ec2_key }} {{ item }}"
#  register: result
#  with_items: 
#     - "{{ groups['all'] }}"
#  tags: 
#     - setup_ssh
#  ignore_errors: True

- name: Create ansible user if not exists
  user:
     name: ansible
     home: "/home/ansible"
     generate_ssh_key: yes
     state: present
     ssh_key_bits: 2048
     ssh_key_file: .ssh/id_rsa
  sudo: true



#- name: Wait for SSH to come up
#  local_action: wait_for 
#    host={{ item.public_ip }} 
#    port=22 
#    state=started
#    connect_timeout={{ ec2-ssh-timeout }}
#  with_items: "{{ ec2.instances }}"

#- name: Add tag to Instance(s)
#  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present aws_access_key={{ec2_access_key}} aws_secret_key={{ec2_secret_key}}
#  with_items: "{{ ec2.instances }}"
#  args:
#    tags:
#      Name: "{{ host_tag }}"
#      auto-gen-source: "ansible"
